export const dealsData = [
  {
    id: 1,
    title: "Zinger Feast",
    desc: "Crispy chicken fillet with cheese & drink.",
    price: "Rs 650",
    image: "/Burger.jpg",
  },
  {
    id: 2,
    title: "Family Platter",
    desc: "2 Large Pizzas, Wings & 1.5L Drink.",
    price: "Rs 2400",
    image: "/Bbq.jpg",
  },
  {
    id: 3,
    title: "Crazy Crunch",
    desc: "5 pcs Fried Chicken with spicy dip.",
    price: "Rs 950",
    image: "/Wraps.jpg",
  },
  {
    id: 4,
    title: "Midnight Deal",
    desc: "Any 2 Burgers with large fries.",
    price: "Rs 1200",
    image: "/Biryani.jpg",
  },
  {
    id: 5,
    title: "Coffee & Cake",
    desc: "Cappuccino with a slice of cheesecake.",
    price: "Rs 850",
    image: "/Burger.jpg",
  },
  {
    id: 6,
    title: "Student Deal",
    desc: "Zinger Burger + Regular Drink.",
    price: "Rs 450",
    image: "/Wraps.jpg",
  },
];

export const menuData = [
  // --- BURGERS ---
  {
    id: 1,
    title: "Zinger Feast",
    desc: "Crispy chicken fillet with cheese & drink.",
    price: "Rs 650",
    image: "/Burger.jpg", // Image path check kr lena
    category: "Burgers",
  },
  {
    id: 2,
    title: "Beef Smash",
    desc: "Juicy beef patty with caramelized onions.",
    price: "Rs 850",
    image: "/Burger.jpg",
    category: "Burgers",
  },
  {
    id: 3,
    title: "Mighty Zinger",
    desc: "Double fillet with spicy mayo sauce.",
    price: "Rs 950",
    image: "/Burger.jpg",
    category: "Burgers",
  },
  {
    id: 4,
    title: "Mighty Zinger",
    desc: "Double fillet with spicy mayo sauce.",
    price: "Rs 950",
    image: "/Burger.jpg",
    category: "Burgers",
  },
  {
    id: 5,
    title: "Mighty Zinger",
    desc: "Double fillet with spicy mayo sauce.",
    price: "Rs 950",
    image: "/Burger.jpg",
    category: "Burgers",
  },
  {
    id: 6,
    title: "Mighty Zinger",
    desc: "Double fillet with spicy mayo sauce.",
    price: "Rs 950",
    image: "/Burger.jpg",
    category: "Burgers",
  },
  {
    id: 7,
    title: "Mighty Zinger",
    desc: "Double fillet with spicy mayo sauce.",
    price: "Rs 950",
    image: "/Burger.jpg",
    category: "Burgers",
  },
  {
    id: 8,
    title: "Mighty Zinger",
    desc: "Double fillet with spicy mayo sauce.",
    price: "Rs 950",
    image: "/Burger.jpg",
    category: "Burgers",
  },

  // --- PIZZA ---
  {
    id: 9,
    title: "Creamy Tikka",
    desc: "Chicken tikka chunks with creamy sauce.",
    price: "Rs 1400",
    image: "/Bbq.jpg", // Placeholder images
    category: "Pizza",
  },
  {
    id: 10,
    title: "Fajita Sensation",
    desc: "Spicy chicken with capsicum and onions.",
    price: "Rs 1350",
    image: "/Bbq.jpg",
    category: "Pizza",
  },
  {
    id: 11,
    title: "Fajita Sensation",
    desc: "Spicy chicken with capsicum and onions.",
    price: "Rs 1350",
    image: "/Bbq.jpg",
    category: "Pizza",
  },
  {
    id: 12,
    title: "Fajita Sensation",
    desc: "Spicy chicken with capsicum and onions.",
    price: "Rs 1350",
    image: "/Bbq.jpg",
    category: "Pizza",
  },
  {
    id: 13,
    title: "Fajita Sensation",
    desc: "Spicy chicken with capsicum and onions.",
    price: "Rs 1350",
    image: "/Bbq.jpg",
    category: "Pizza",
  },
  {
    id: 14,
    title: "Fajita Sensation",
    desc: "Spicy chicken with capsicum and onions.",
    price: "Rs 1350",
    image: "/Bbq.jpg",
    category: "Pizza",
  },
  {
    id: 15,
    title: "Fajita Sensation",
    desc: "Spicy chicken with capsicum and onions.",
    price: "Rs 1350",
    image: "/Bbq.jpg",
    category: "Pizza",
  },
  {
    id: 16,
    title: "Fajita Sensation",
    desc: "Spicy chicken with capsicum and onions.",
    price: "Rs 1350",
    image: "/Bbq.jpg",
    category: "Pizza",
  },

  // --- SANDWICHES ---
  {
    id: 17,
    title: "Club Sandwich",
    desc: "Classic triple layer toasted sandwich.",
    price: "Rs 550",
    image: "/Wraps.jpg",
    category: "Sandwich",
  },
  {
    id: 18,
    title: "BBQ Sandwich",
    desc: "Smoky chicken filling with cheese.",
    price: "Rs 600",
    image: "/Wraps.jpg",
    category: "Sandwich",
  },

  {
    id: 19,
    title: "Loaded Fries",
    desc: "Fries topped with cheese and jalapeños.",
    price: "Rs 500",
    image: "/Biryani.jpg",
    category: "Starters",
  },
  {
    id: 20,
    title: "Nuggets (6pcs)",
    desc: "Golden crispy chicken nuggets.",
    price: "Rs 400",
    image: "/Biryani.jpg",
    category: "Starters",
  },
];
